
[project]
name = "image-text-retrieval-challenge"
version = "0.1.0"
description = "A challenge to translate text embeddings to image embeddings."
authors = ["Mamiglia"]
requires-python = ">=3.11"
dependencies = [
    "torch",
    "transformers",
    "datasets",
    "faiss-cpu",
    "sentence-transformers",
    "tqdm",
    "Pillow",
    "matplotlib",
    "scikit-learn",
    "gdown"
]
